# Generated by Django 3.2.8 on 2021-12-05 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apprevista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('date_crea', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('user_mod', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('titulo', models.CharField(help_text='Titulo de la publicación', max_length=150, unique=True)),
                ('descrip_publ', models.CharField(max_length=1000, verbose_name='descripcion publicación')),
                ('imag_prod', models.ImageField(null=True, upload_to='imagen_user', verbose_name='imagen publicación')),
                ('subcateg_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apprevista.subcategoria_r')),
                ('user_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
                'unique_together': {('subcateg_r', 'titulo')},
            },
        ),
    ]
