# Generated by Django 3.2.8 on 2021-12-05 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appcatalogo', '0007_alter_descuento_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcompra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='est_pago',
            field=models.CharField(blank=True, max_length=15, verbose_name='estado pago'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cod_factura',
            field=models.CharField(help_text='codigo factura', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductoInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('date_crea', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('user_mod', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('date_observa', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date observa')),
                ('est_pago', models.CharField(max_length=15, verbose_name='estado pago')),
                ('descrip_prod', models.CharField(max_length=200, verbose_name='descripcion producto')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcompra.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcatalogo.producto')),
                ('user_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ProductosInteres',
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('date_crea', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('user_mod', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('descrip_pedido', models.CharField(blank=True, help_text='Descripción del pedido', max_length=1000)),
                ('descrip_estado', models.CharField(blank=True, help_text='Descripción del estado', max_length=500)),
                ('cod_factura', models.CharField(max_length=50, verbose_name='codigo factura')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcompra.factura')),
                ('user_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'EstadoPedidos',
            },
        ),
    ]
