# Generated by Django 3.2.8 on 2021-12-05 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appcompra', '0002_auto_20211204_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productointeres',
            name='date_observa',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha/hora que observo un producto', verbose_name='date observa'),
        ),
    ]
