# Generated by Django 3.2.8 on 2021-10-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='date_birth',
            field=models.DateField(null=True, verbose_name='fecha nacimiento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='cedula'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='num_cell',
            field=models.CharField(blank=True, max_length=20, verbose_name='numero celular'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='num_telf',
            field=models.CharField(blank=True, max_length=20, verbose_name='numero telefono'),
        ),
    ]
