# Generated by Django 3.2.8 on 2021-11-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0005_usuario_cod_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=25, verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=60, verbose_name='direccion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.CharField(blank=True, max_length=20, verbose_name='pais'),
        ),
    ]
