# Generated by Django 3.2.8 on 2021-11-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0006_auto_20211121_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dni_tipo',
            field=models.CharField(blank=True, max_length=15, verbose_name='tipo documento'),
        ),
    ]
