# Generated by Django 3.2.8 on 2021-11-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0007_usuario_dni_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user_mod',
            field=models.IntegerField(blank=True, null=True, verbose_name='usuario modifica'),
        ),
    ]
