# Generated by Django 3.2.8 on 2021-11-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0008_usuario_user_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user_crea',
            field=models.IntegerField(blank=True, null=True, verbose_name='usuario crea'),
        ),
    ]
