# Generated by Django 3.2.8 on 2021-11-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0009_usuario_user_crea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica si el usuario puede iniciar sesión en admin.', verbose_name='es staff'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_crea',
            field=models.IntegerField(blank=True, help_text='Indica que usuario creo a cual usuario', null=True, verbose_name='usuario crea'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_mod',
            field=models.IntegerField(blank=True, help_text='Indica que usuario modifico a cual usuario', null=True, verbose_name='usuario modifica'),
        ),
    ]
