# Generated by Django 3.2.8 on 2021-11-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0010_auto_20211121_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_crea',
            field=models.EmailField(blank=True, help_text='Indica que usuario creo a cual usuario', max_length=254, null=True, verbose_name='usuario crea'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_mod',
            field=models.EmailField(blank=True, help_text='Indica que usuario modifico a cual usuario', max_length=254, null=True, verbose_name='usuario modifica'),
        ),
    ]
