# Generated by Django 3.2.8 on 2021-12-05 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('date_crea', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('user_mod', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('descripcion', models.CharField(help_text='Descripción de las actividades', max_length=200, unique=True)),
                ('user_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria_Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('date_crea', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('user_mod', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('descripcion', models.CharField(help_text='Descripción de la subcategoria', max_length=100)),
                ('categ_activ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appactividades.categoria_act')),
                ('user_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SubCategorias',
                'unique_together': {('categ_activ', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('date_crea', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('user_mod', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('titulo', models.CharField(help_text='Titulo de la publicación', max_length=150, unique=True)),
                ('descrip_act', models.CharField(max_length=1000, verbose_name='descripcion publicación')),
                ('date_inicio', models.DateField(null=True, verbose_name='fecha/hora inicio')),
                ('date_fin', models.DateField(null=True, verbose_name='fecha/hora fin')),
                ('recordar', models.BooleanField(default=False, verbose_name='recordatorio')),
                ('tiempo_recordar', models.IntegerField(default=0, verbose_name='tiempo recordatorio')),
                ('subcateg_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appactividades.subcategoria_act')),
                ('user_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
                'unique_together': {('subcateg_act', 'titulo')},
            },
        ),
    ]
