# Generated by Django 3.2.8 on 2021-12-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appactividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='realizo_act',
            field=models.BooleanField(default=False, verbose_name='realizo actividad'),
        ),
        migrations.AlterField(
            model_name='categoria_act',
            name='descripcion',
            field=models.CharField(help_text='Descripción de las actividades', max_length=100, unique=True),
        ),
    ]
