"""
Django settings for appgotogym project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
#import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9vw*mfq4%bun)_ei&hcv&*gs=n22=-_19ge6c&fw@7wl_a5g=p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

##Credenciales para autenticar con facebook.
SOCIAL_AUTH_FACEBOOK_KEY = "1057090698447701"
SOCIAL_AUTH_FACEBOOK_SECRET = "16ab46ce7d8ef2cc07c84dbc9c8c6d13"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'applogin', ##Se agrego la aplicación para el inicio de sesion y el home
    'social_django', ##app para autenticar con facebook
    'appcatalogo', ##se agrego la aplicación para los catalogos de productos
    'appcompra', ##se agrego la aplicación para las compras realizadas y facturadas
    'appplan', ##se agrego la aplicación para los planes
    'apprevista', ##se agrego la aplicación para la revista
    'appactividades', ##se agrego la aplicación para las appactividades
    'apppregbienestar', ##se agrego la aplicación para las pregutas de bienestar
    'apppregexperiencia', ##se agrego la aplicación para las preguntas de la experiencia y satisfacción
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'appgotogym.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], #Directorio donde se crearan las vistas
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]


#obtener campos adicionales desde facebook
#con esta configuracion podemos traer el email y la imagen

SOCIAL_AUTH_FACEBOOK_SCOPE = ['email', 'user_link']

SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id, name, email, picture.type(large), link'
}


SOCIAL_AUTH_FACEBOOK_EXTRA_DATA = [
    ('name', 'name'),
    ('email', 'email'),
    ('picture', 'picture'),
    ('link', 'profile_url'),
]

##
WSGI_APPLICATION = 'appgotogym.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'db_gotogym',
        'USER': 'postgres',
        'PASSWORD': 'TFM@2021',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

###Definimos donde estara ubicado los ficheros para el diseño de la pagina.
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]


#import os   ##linea de prueba para subir imagen
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')    ##linea de prueba para subir imagen
MEDIA_ROOT = (BASE_DIR / 'media')  #linea original
MEDIA_URL = '/media/'


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/home/'
##LOGOUT_REDIRECT_URL = '/login/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'applogin.Usuario'


##guardar los datos de la autenticacion de facebook en las tablas.
AUTHENTICATION_BACKENDS = [
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

##Envio de mensaje desde "Contactenos"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'ricardoleonardo.parrales107@comunidadunir.net'  #correo de donde saldran los mensajes
EMAIL_HOST_PASSWORD = '1512@ngie'
#EMAIL_CONTEXT = ssl.create_default_context()