# Generated by Django 3.2.8 on 2021-12-05 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appcompra', '0003_alter_productointeres_date_observa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoplan',
            name='descripcion',
            field=models.CharField(help_text='Descripción del tipo de plan', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoplan',
            name='tipo_plan',
            field=models.CharField(max_length=20, verbose_name='tipo plan'),
        ),
        migrations.CreateModel(
            name='Contratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('date_crea', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('user_mod', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('descripcion', models.CharField(max_length=20, verbose_name='tipo plan')),
                ('est_pago', models.CharField(max_length=15, verbose_name='estado pago')),
                ('date_contratado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha registro')),
                ('date_vence', models.DateField(null=True, verbose_name='fecha vence plan')),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcompra.factura')),
                ('tipoplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appplan.tipoplan')),
                ('user_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contratados',
                'unique_together': {('tipoplan', 'user_crea')},
            },
        ),
    ]
