# Generated by Django 3.2.8 on 2021-12-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appplan', '0002_auto_20211205_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratado',
            name='date_contratado',
        ),
    ]
