# Generated by Django 3.2.8 on 2021-12-05 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_PB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('date_crea', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('user_mod', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('descripcion', models.CharField(help_text='Descripción de la categoria', max_length=100, unique=True)),
                ('user_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='SubCategoria_PB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('date_crea', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('user_mod', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('descripcion', models.CharField(help_text='Descripción de la subcategoria', max_length=100)),
                ('categ_pb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apppregbienestar.categoria_pb')),
                ('user_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SubCategorias',
                'unique_together': {('categ_pb', 'descripcion')},
            },
        ),
        migrations.CreateModel(
            name='Preg_Bienestar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('date_crea', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('user_mod', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('titulo', models.CharField(help_text='Titulo de la pregunta de bienestar.', max_length=150, unique=True)),
                ('descrip_pb', models.CharField(max_length=1000, verbose_name='descripcion publicación')),
                ('date_inicio', models.DateField(null=True, verbose_name='fecha/hora inicio')),
                ('date_fin', models.DateField(null=True, verbose_name='fecha/hora fin')),
                ('recordar', models.BooleanField(default=False, verbose_name='recordatorio')),
                ('tiempo_recordar', models.IntegerField(default=0, verbose_name='tiempo recordatorio')),
                ('respuesta_pb', models.CharField(blank=True, max_length=2, verbose_name='recordatorio')),
                ('subcateg_pb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apppregbienestar.subcategoria_pb')),
                ('user_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Publicaciones',
                'unique_together': {('subcateg_pb', 'titulo')},
            },
        ),
    ]
