# Generated by Django 3.2.8 on 2021-12-04 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcatalogo', '0003_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('date_crea', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('user_mod', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('descripcion', models.CharField(help_text='Descripción de la Marca', max_length=100, unique=True)),
                ('cant_desc', models.IntegerField(default=0, verbose_name='cantidad del descuento')),
                ('user_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Descuentos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('date_crea', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('date_mod', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('user_mod', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('num_serie', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('codigo_barra', models.CharField(max_length=50, verbose_name='código de barra')),
                ('precio', models.FloatField(default=0, verbose_name='precio del producto')),
                ('cant_existencia', models.IntegerField(default=0, verbose_name='cantidad en existencia')),
                ('ultima_compra', models.DateField(blank=True, null=True, verbose_name='ultima compra')),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcatalogo.descuento')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcatalogo.marca')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcatalogo.subcategoria')),
                ('user_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'unique_together': {('num_serie', 'codigo_barra')},
            },
        ),
    ]
