# Generated by Django 3.2.8 on 2021-12-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatalogo', '0006_alter_producto_imag_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='descripcion',
            field=models.CharField(help_text='Descripción del descuento', max_length=100, unique=True),
        ),
    ]
