# Generated by Django 3.2.8 on 2021-12-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcatalogo', '0007_alter_descuento_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la subcategoria', max_length=100),
        ),
    ]
